name: Deploy Space Design Aurora FE

# Trigger del workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout del repository nella directory di destinazione
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Sostituisci con la versione di Node.js che desideri usare

      # Step 3: Installazione delle dipendenze
      - name: Install dependencies
        run: |
          cd /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it
          npm install

      # Step 4: Build del progetto
      - name: Build project
        run: |
          cd /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it
          npm run build

      # Step 5: Verifica della cartella dist
      - name: Check if dist folder exists
        run: |
          cd /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it
          if [ -d "dist" ]; then
            echo "dist folder found!"
          else
            echo "dist folder not found!"
            exit 1
          fi

      # Step 6: Listare il contenuto della cartella dist (se presente)
      - name: List contents of dist directory
        run: |
          cd /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it
          ls -R dist || echo "No dist folder found"
