name: Deploy Space Design Aurora FE

# Trigger per eseguire il workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurazione di Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3

      # Step 3: Installazione delle dipendenze
      - name: Install dependencies
        run: npm i

      # Step 4: Verifica dei permessi sulla cartella
      - name: Check permissions of target directory
        run: ls -ld /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it

      # Step 5: Verifica della struttura del progetto prima della build
      - name: List project directory contents
        run: ls -R

      # Step 6: Build del progetto con opzioni di debug
      - name: Build project
        run: npm run build

      # Step 7: Verifica se la cartella dist è stata creata
      - name: Check if dist folder exists
        run: |
          if [ -d "dist" ]; then
            echo "dist folder found!"
          else
            echo "dist folder not found!"
            exit 1
          fi

      # Step 8: Elenco contenuto della cartella dist (se presente)
      - name: List contents of dist directory
        run: ls -R dist || echo "No dist folder found"
