name: Deploy SpaceDesignAurora FE

on:
  push:
    branches:
      - main  # Puoi cambiare 'main' con il branch da cui vuoi fare il deploy

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilizza un runner GitHub ospitato

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Sostituisci con la versione di Node.js che usi

      - name: Install dependencies
        run: |
          npm install

      - name: Build React app
        run: |
          npm run build

      - name: Deploy to Ubuntu server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          key: ${{ secrets.PLESK_SSH_KEY }}
          port: 22  # Modifica se il tuo server usa una porta diversa
          script: |
            cd /var/www/vhosts/spacedesign-italia.it/app.spacedesign-italia.it
            rm -rf *
            cp -r /tmp/build/* .  # Copia la build dal runner al server
